#!/usr/bin/python3 -sS

import sys

input_file, solution_file, output_file = sys.argv[1:]

# We assume input and solution files are well-formed.
with open(input_file, 'r') as f:
    number = int(f.readline())
with open(solution_file, 'r') as f:
    solution_word = f.readline().split()[0]

# Ensure output is of the form "<word> <number>" where word is from the
# solution, and number is from the student.
try:
    with open(output_file, 'r') as f:
        line = f.readline().strip()
        more = f.readline()
    if line == '%s %d' % (solution_word, number) and more == '':
        print("1.0")
        print("Correcto", file=sys.stderr)
    else:
        assert more == ''
        print("0.0")
        print("Plain wrong", file=sys.stderr)
except:
    # Given the file comes from the manager, it really should have been
    # correct.
    raise
