#!/usr/bin/python3 -sS

import sys

fifo_path_from_user1, fifo_path_to_user1, \
    fifo_path_from_user2, fifo_path_to_user2 = sys.argv[1:]

# When the sandbox opens the other endpoints of these fifos to redirect
# them to to stdin/out it does so first for stdin and then for stdout.
# We must match that order as otherwise we would deadlock.
fifo_to_user1 = open(fifo_path_to_user1, "w")
fifo_from_user1 = open(fifo_path_from_user1, "r")
fifo_to_user2 = open(fifo_path_to_user2, "w")
fifo_from_user2 = open(fifo_path_from_user2, "r")

with open("input.txt", "r") as f:
    input_value = int(f.readline())

correct = True

# Speak the to program a few times, check what it does, and output the last
# line.
for i in [*range(10, 20), 0]:
    x = i + input_value
    # Write a question to the candidate executable.
    print(x, file=fifo_to_user1, flush=True)
    # Read their response.
    l = fifo_from_user1.readline()
    # EOF?
    if l == '':
        correct = False
        break
    # These are the only things we expect from our stub.
    if l.strip() != 'correct %d' % x:
        correct = False
        break

    correct = correct and (int(l.split()[1]) == x)

    # Write a question to the candidate executable.
    print(x, file=fifo_to_user2, flush=True)
    # Read their response.
    l = fifo_from_user2.readline()
    # EOF?
    if l == '':
        correct = False
        break
    # These are the only things we expect from our stub.
    if l.strip() != 'correct %d' % (-x):
        correct = False
        break

    correct = correct and (int(l.split()[1]) == -x)
else:
    # Tell stub to exit.
    print(0, file=fifo_to_user1, flush=True)
    print(0, file=fifo_to_user2, flush=True)

# This file exists just for convenience.
with open("output.txt", "w") as f:
    print(l, file=f)

# This is the final score.
if correct:
    print("1")
else:
    print("0")
