#!/usr/bin/python3 -sS

import sys

input_file, solution_file, output_file = sys.argv[1:]

# We just check if the first number in the output and solution are the same.
with open(output_file, 'r') as f:
    output_number = int(f.readline())
with open(solution_file, 'r') as f:
    solution_number = int(f.readline())

if output_number == solution_number:
    print("1.0")
    print("Correcto", file=sys.stderr)
else:
    print("0.0")
    print("Plain wrong", file=sys.stderr)
